update semver

diff --git a/.github/workflows/changelog-release.yml b/.github/workflows/changelog-release.yml
--- a/.github/workflows/changelog-release.yml
+++ b/.github/workflows/changelog-release.yml
@@ -17,7 +17,18 @@ jobs:
       - name: Update Changelog
         id: update_changelog
         run: |
-          RELEASE_VERSION="${{ env.release_version }}"
+          RELEASE_VERSION="${{ github.event.release.tag_name }}"
+
+          # SemVer regex validation
+          SEMVER_REGEX="^(v)?([0-9]+)(\.)([0-9]+)(\.)([0-9]+)(|-[a-z]+(\.)[0-9]+)$"
+
+          if [[ ! "$RELEASE_TAG" =~ $SEMVER_REGEX ]]; then
+            echo "Error: Release tag '$RELEASE_TAG' is not a valid Semantic Version."
+            exit 1
+          fi
+
+          echo "release tag: $RELEASE_VERSION"
+          echo "release_version=$RELEASE_VERSION" >> $GITHUB_ENV
           RELEASE_DATE=$(date +'%Y-%m-%d')
 
           # Ensure CHANGELOG.md exists
